{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Tamil-Fuzionest",
    "module": "BizSub-SDK",
    "version": "v1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.razorpay",
          "module": "checkout",
          "version": {
            "requires": "1.6.41"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "BizSub-SDK-v1.0.9.aar",
          "url": "BizSub-SDK-v1.0.9.aar",
          "size": 23275,
          "sha512": "2e60b0f1d01d93ec1b113e89206a4b02a1fdd685c11d602b7ce5e900b456f9656a049fe78bfd4ba6c09d28fcd2c3bc269660a86bc4face09b616cd63134ff3f4",
          "sha256": "44e0172ea53e9d2afe5abf096cfd2d2153bb6e4505db449ec18d18f628fec114",
          "sha1": "47edb36b031f7206f21ccb35e94bad5aef0aed73",
          "md5": "629310547cfd0b7f8f1f0b73c6a8d418"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.razorpay",
          "module": "checkout",
          "version": {
            "requires": "1.6.41"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "BizSub-SDK-v1.0.9.aar",
          "url": "BizSub-SDK-v1.0.9.aar",
          "size": 23275,
          "sha512": "2e60b0f1d01d93ec1b113e89206a4b02a1fdd685c11d602b7ce5e900b456f9656a049fe78bfd4ba6c09d28fcd2c3bc269660a86bc4face09b616cd63134ff3f4",
          "sha256": "44e0172ea53e9d2afe5abf096cfd2d2153bb6e4505db449ec18d18f628fec114",
          "sha1": "47edb36b031f7206f21ccb35e94bad5aef0aed73",
          "md5": "629310547cfd0b7f8f1f0b73c6a8d418"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BizSub-SDK-v1.0.9-sources.jar",
          "url": "BizSub-SDK-v1.0.9-sources.jar",
          "size": 5725,
          "sha512": "1d0cbe607ae26bc2019dadfe9e9b1482a18c1ad9a9a1adc52e49a40dc6c82d828952f0ca7114ccdd88d20889bebb3dcd75f26d1133372036b58cd33b6c413bf1",
          "sha256": "8af5dfa14561f3f17b7f8031952f7e09cd04312f8f02feda893d88c0933ec665",
          "sha1": "a1169ac67df1349d02cd2a320e22470fa58b06dc",
          "md5": "5357e28bb0b433dca524bcc13613b2f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BizSub-SDK-v1.0.9-javadoc.jar",
          "url": "BizSub-SDK-v1.0.9-javadoc.jar",
          "size": 297346,
          "sha512": "d0492dfd486b1030a48ed43ec6c970b8c5d30e594a718a19adf5b84bdf20cc10b11bf18dd8bfa88ce302d1f9e90bb2381e2c87591d71bb817df32904a6b3e5c2",
          "sha256": "2978e69ca99d4510b310aaeb9dd004f81718c016460e6a89eabe0cb609d7dc42",
          "sha1": "5d31b1d24efe8f3c7bdfbfa01ef29d545f593b65",
          "md5": "3b66049cf66f3cffdb120680ea49b0de"
        }
      ]
    }
  ]
}
